"use client";
import {useRef,useState} from "react";
type Tab="home"|"create"|"chat"|"profile";
const seed=[
 {id:1,user:"Haojue Uganda",tag:"@haojueug · 12 min",text:"Built for the road. Ready for your next chapter. 🏍️🔥 #ChooseQuality",img:"https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85",likes:248},
 {id:2,user:"Amina K.",tag:"@aminak · 1 hr",text:"Golden hour in Jinja. Uganda really is beautiful. 🇺🇬",img:"https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=1200&q=85",likes:183}
];
export default function Home(){
 const [login,setLogin]=useState(false),[sent,setSent]=useState(false),[phone,setPhone]=useState(""),[otp,setOtp]=useState("");
 const [tab,setTab]=useState<Tab>("home"),[posts,setPosts]=useState(seed),[caption,setCaption]=useState(""),[media,setMedia]=useState(""),[video,setVideo]=useState(false),[liked,setLiked]=useState<number[]>([]);
 const [msg,setMsg]=useState(""),[messages,setMessages]=useState(["Hi Luuba! I saw your new post.","Thank you! How can I help you?"]); const file=useRef<HTMLInputElement>(null);
 const share=(t:string)=>window.open("https://wa.me/?text="+encodeURIComponent(t+" — Shared from Luuba Connect"),"_blank");
 if(!login)return <main className="login"><section><b className="logo">L</b><label>LUUBA CONNECT</label><h1>Uganda,<br/>connected.</h1><p>Share moments, chat with your people, and take your story everywhere.</p><div className="phone"><b>🇺🇬 +256</b><input inputMode="tel" placeholder="7XX XXX XXX" value={phone} onChange={e=>setPhone(e.target.value)}/></div>{sent&&<input className="otp" placeholder="Enter code (123456)" value={otp} onChange={e=>setOtp(e.target.value)}/>}<button className="primary" disabled={!sent?phone.replace(/\D/g,"").length<9:otp!=="123456"} onClick={()=>sent?setLogin(true):setSent(true)}>{sent?"Verify & enter →":"Continue with phone →"}</button><small>Demo verification code: <b>123456</b></small></section><aside><div><span>CREATE • CHAT • SHARE</span><h2>Your people.<br/>Your stories.<br/>One place.</h2></div></aside></main>;
 const nav=(id:Tab,icon:string,name?:string)=><button className={tab===id?"active":""} onClick={()=>setTab(id)}><i>{icon}</i>{name}</button>;
 return <main className="app"><aside className="side"><div className="brand"><b className="logo">L</b>Luuba</div><nav>{nav("home","⌂","Home")}{nav("create","＋","Create")}{nav("chat","◌","Messages")}{nav("profile","◎","Profile")}</nav><div className="links"><small>CONNECTED PLATFORMS</small><a href="https://tiktok.com" target="_blank">♪ TikTok ↗</a><a href="https://youtube.com" target="_blank">▶ YouTube ↗</a><a href="https://wa.me" target="_blank">◉ WhatsApp ↗</a></div><button className="me"><b>LC</b><span>Luuba Creator<small>Verified member</small></span></button></aside>
 <section className="main"><header><b className="mobile-logo">L</b><div className="search">⌕ <input placeholder="Search people, posts and videos"/></div><button>♡</button><b className="avatar">LS</b></header>
 {tab==="home"&&<div className="feed"><div className="stories">{[["Your story","LS"],["Amina","AK"],["Jinja Rides","JR"],["Brian","BM"],["Haojue UG","HJ"]].map(x=><button key={x[0]}><b>{x[1]}</b><small>{x[0]}</small></button>)}</div><div className="compose"><b className="avatar">LS</b><button onClick={()=>setTab("create")}>Share a photo, video or thought…</button><button onClick={()=>setTab("create")}>▧ Media</button></div>{posts.map(p=><article key={p.id}><div className="posthead"><b className="avatar">{p.user.slice(0,2)}</b><span><strong>{p.user}</strong><small>{p.tag}</small></span><button>•••</button></div><p>{p.text}</p><img src={p.img} alt="Post media"/><div className="stats"><span>{p.likes+(liked.includes(p.id)?1:0)} likes</span><span>36 comments</span></div><footer><button className={liked.includes(p.id)?"hot":""} onClick={()=>setLiked(v=>v.includes(p.id)?v.filter(i=>i!==p.id):[...v,p.id])}>♥ Like</button><button>◯ Comment</button><button onClick={()=>share(p.text)}>↗ Share</button></footer></article>)}</div>}
 {tab==="create"&&<div className="card create"><label>NEW POST</label><h2>Share your story</h2><textarea placeholder="What is happening?" value={caption} onChange={e=>setCaption(e.target.value)}/><input hidden ref={file} type="file" accept="image/*,video/*" onChange={e=>{const f=e.target.files?.[0];if(f){setVideo(f.type.startsWith("video"));setMedia(URL.createObjectURL(f))}}}/><button className="drop" onClick={()=>file.current?.click()}>{media?(video?<video src={media} controls/>:<img src={media} alt="Preview"/>):<><i>＋</i><b>Add a photo or video</b><small>Tap to choose from your device</small></>}</button><div className="publish"><span>📍 Location　☺ Feeling</span><button className="primary" onClick={()=>{if(media||caption){setPosts([{id:Date.now(),user:"Luuba Creator",tag:"@creator · now",text:caption||"New post",img:media||seed[0].img,likes:0},...posts]);setCaption("");setMedia("");setTab("home")}}}>Publish post</button></div></div>}
 {tab==="chat"&&<div className="chatbox"><aside><h2>Messages</h2>{[["AK","Amina K."],["JR","Jinja Rides"],["BM","Brian M."]].map((x,i)=><button className={i?"":"selected"} key={x[1]}><b>{x[0]}</b><span>{x[1]}<small>{i?"Let’s collaborate":"Hi Luuba! I saw your…"}</small></span></button>)}</aside><section><div className="chathead"><b className="avatar">AK</b><span>Amina K.<small>● Active now</small></span></div><div className="bubbles">{messages.map((m,i)=><p className={i%2?"mine":""} key={i}>{m}</p>)}</div><form onSubmit={e=>{e.preventDefault();if(msg){setMessages([...messages,msg]);setMsg("")}}}><input placeholder="Write a message…" value={msg} onChange={e=>setMsg(e.target.value)}/><button>➤</button></form></section></div>}
 {tab==="profile"&&<div className="card profile"><div className="cover"/><div className="person"><b>LC</b><span><h2>Luuba Creator</h2><small>@creator · Jinja, Uganda 🇺🇬</small></span><button onClick={()=>setLogin(false)}>Log out</button></div><p>Media creator, motorcycle marketing professional and storyteller. Connecting Uganda, one story at a time.</p><div className="numbers"><b>{posts.length}<small> Posts</small></b><b>1.8K<small> Followers</small></b><b>426<small> Following</small></b></div><div className="platforms"><a href="https://wa.me/" target="_blank">◉ <b>WhatsApp<small>Open chat</small></b> ↗</a><a href="https://tiktok.com" target="_blank">♪ <b>TikTok<small>Connect profile</small></b> ↗</a><a href="https://youtube.com" target="_blank">▶ <b>YouTube<small>Connect channel</small></b> ↗</a></div></div>}
 </section><nav className="mobile">{nav("home","⌂")}{nav("create","＋")}{nav("chat","◌")}{nav("profile","◎")}</nav></main>
}
